state.VAMPIRE.SoundScape = {
    trackDetails: {
        "Plague Tale 4": {
            id: "-LtZ0_Pf66HHz8ZzOOJn",
            title: "Plague Tale 4",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 15": {
            id: "-LtZ0_jnAeRWQ7hV4fVa",
            title: "Plague Tale 15",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: null
        },
        "Plague Tale 14": {
            id: "-LtZ0_jrN8XvHSlm4gB-",
            title: "Plague Tale 14",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 13": {
            id: "-LtZ0_jv99WNaPiX1ho2",
            title: "Plague Tale 13",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 12": {
            id: "-LtZ0_jyoL09lXVhgONz",
            title: "Plague Tale 12",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 11": {
            id: "-LtZ0_k1sx3hxXsQxaYw",
            title: "Plague Tale 11",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 10": {
            id: "-LtZ0_k663N1yaQhDpQp",
            title: "Plague Tale 10",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 8": {
            id: "-LtZ0_kAwYus43N3G1cU",
            title: "Plague Tale 8",
            playing: true,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 7": {
            id: "-LtZ0_kIrmDV0ZkdCbnb",
            title: "Plague Tale 7",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 6": {
            id: "-LtZ0_kOlneli_xHZ7Pb",
            title: "Plague Tale 6",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 5": {
            id: "-LtZ0_kU19INqgpcurSc",
            title: "Plague Tale 5",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 3": {
            id: "-LtZ0_kfks5QpYed16YB",
            title: "Plague Tale 3",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 2": {
            id: "-LtZ0_klMdDapG40CFa-",
            title: "Plague Tale 2",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        "Plague Tale 1": {
            id: "-LtZ0_krxY6fTsjJdTIY",
            title: "Plague Tale 1",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0,
            who: "gm"
        },
        WindWinterMax: {
            id: "-LtZ4UGP6NpfnaU2AGW2",
            title: "WindWinterMax",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        WindWinterMed: {
            id: "-LtZ4UG_kKv566z92UP-",
            title: "WindWinterMed",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 90,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        },
        WindWinterLow: {
            id: "-LtZ4UGiWakjUK6RZ1Ol",
            title: "WindWinterLow",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        WindMax: {
            id: "-LtZ4UGtTFqOCshKgNmq",
            title: "WindMax",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        WindMed: {
            id: "-LtZ4UH33RFBj3Qh623E",
            title: "WindMed",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        WindLow: {
            id: "-LtZ4UHCxd6M3HVoMATb",
            title: "WindLow",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        Rain: {
            id: "-LtZ4UHNZpC-1wRVlr19",
            title: "Rain",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        Thunder3: {
            id: "-LtZ4UT72gsPLS4PyaWG",
            title: "Thunder3",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 7,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        Thunder2: {
            id: "-LtZ4UTJ8Wc5NUyyzGnc",
            title: "Thunder2",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 7,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        Thunder1: {
            id: "-LtZ4UTUGSrmzfP1Lrqk",
            title: "Thunder1",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 7,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        WolfHowl: {
            id: "-LtZ4UcptDJyClqdLYqj",
            title: "WolfHowl",
            playing: false,
            access: "gm",
            mode: "single",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        },
        Subway: {
            id: "-LtZ4Un0Bkh1pWLGN3Sj",
            title: "Subway",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        Sewers: {
            id: "-LtZ4UnK3lVkc35wHH-6",
            title: "Sewers",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 45,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        },
        Waterside: {
            id: "-LtZ4UnW1fAhW6weE6D1",
            title: "Waterside",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        CityWalking: {
            id: "-LtZ4UnidH3XIrRA6yAn",
            title: "CityWalking",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 40,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        },
        IndoorMarket: {
            id: "-LtZ4UnxXrsr644VfuDy",
            title: "IndoorMarket",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        CityTraffic: {
            id: "-LtZ4Uo9yYpKteUpnpxA",
            title: "CityTraffic",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        CityRevelers: {
            id: "-LtZ4Uob0-hBdhA1P9Ka",
            title: "CityRevelers",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 45,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        },
        DiveBar: {
            id: "-LtZ4Uot_cqR-xwkZq6J",
            title: "DiveBar",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 45,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        },
        CitySuburb: {
            id: "-LtZ4Up91GgUYesNgJrv",
            title: "CitySuburb",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 45,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        },
        CityChatter: {
            id: "-LtZ4UpWSW6_X_Tlb3Hr",
            title: "CityChatter",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        SoftHum: {
            id: "-LtZ4UpkHXfYsIvwW_Sw",
            title: "SoftHum",
            playing: true,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 45,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        },
        Nightclub: {
            id: "-LtZ4UqCnVa6Qe-YrRAr",
            title: "Nightclub",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        Office: {
            id: "-LtZ4UqUOk0ChzxbmpUZ",
            title: "Office",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        Hospital: {
            id: "-LtZ4UqjaqxkrdEY_i8L",
            title: "Hospital",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        UrbanDark: {
            id: "-LtZ4Ur9-hYdVcUHtyn1",
            title: "UrbanDark",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 45,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        },
        Industry: {
            id: "-LtZ4UrWu1TnFEZ24Ikr",
            title: "Industry",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        RoofTop: {
            id: "-LtZ4UrnSKPXFZtYvcwl",
            title: "RoofTop",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        Airport: {
            id: "-LtZ4UsLzT9n9zN3OzJ_",
            title: "Airport",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: null
        },
        Church: {
            id: "-LtZ4UsilVwicijtu_io",
            title: "Church",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 60,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        },
        SoftIndoor: {
            id: "-LtZ4Ut262h4-l8XJiZH",
            title: "SoftIndoor",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 30,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        },
        CityPark: {
            id: "-LtZ4UtMRs7TvvA053_6",
            title: "CityPark",
            playing: false,
            access: "gm",
            mode: "loop",
            delay: 0,
            tags: [ "Off", "Off", "Off", "Off", "Off" ],
            volume: 80,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0",
            who: "gm"
        }
    },
    playLists: {
        Locations: {
            name: "Locations",
            trackids: [
                "-LtZ4UtMRs7TvvA053_6",
                "-LtZ4Ut262h4-l8XJiZH",
                "-LtZ4UsilVwicijtu_io",
                "-LtZ4UsLzT9n9zN3OzJ_",
                "-LtZ4UrnSKPXFZtYvcwl",
                "-LtZ4UrWu1TnFEZ24Ikr",
                "-LtZ4Ur9-hYdVcUHtyn1",
                "-LtZ4UqjaqxkrdEY_i8L",
                "-LtZ4UqUOk0ChzxbmpUZ",
                "-LtZ4UqCnVa6Qe-YrRAr",
                "-LtZ4UpkHXfYsIvwW_Sw",
                "-LtZ4UpWSW6_X_Tlb3Hr",
                "-LtZ4Up91GgUYesNgJrv",
                "-LtZ4Uot_cqR-xwkZq6J",
                "-LtZ4Uob0-hBdhA1P9Ka",
                "-LtZ4Uo9yYpKteUpnpxA",
                "-LtZ4UnxXrsr644VfuDy",
                "-LtZ4UnidH3XIrRA6yAn",
                "-LtZ4UnW1fAhW6weE6D1",
                "-LtZ4UnK3lVkc35wHH-6",
                "-LtZ4Un0Bkh1pWLGN3Sj"
            ],
            shuffleIds: [ ],
            playing: true,
            currentTrack: [ ],
            lastTrack: null,
            access: "gm",
            mode: "shuffle",
            delay: 0,
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0"
        },
        Effects: {
            name: "Effects",
            trackids: [ "-LtZ4UcptDJyClqdLYqj" ],
            shuffleIds: [ ],
            playing: false,
            currentTrack: [ ],
            lastTrack: null,
            access: "gm",
            mode: "single",
            delay: 0,
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0"
        },
        Thunder: {
            name: "Thunder",
            trackids: [ "-LtZ4UTUGSrmzfP1Lrqk", "-LtZ4UTJ8Wc5NUyyzGnc", "-LtZ4UT72gsPLS4PyaWG" ],
            shuffleIds: [ ],
            playing: false,
            currentTrack: [ ],
            lastTrack: null,
            access: "gm",
            mode: "randomSingle",
            delay: 0,
            volume: 7,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0"
        },
        Weather: {
            name: "Weather",
            trackids: [
                "-LtZ4UHNZpC-1wRVlr19",
                "-LtZ4UHCxd6M3HVoMATb",
                "-LtZ4UH33RFBj3Qh623E",
                "-LtZ4UGtTFqOCshKgNmq",
                "-LtZ4UGiWakjUK6RZ1Ol",
                "-LtZ4UG_kKv566z92UP-",
                "-LtZ4UGP6NpfnaU2AGW2"
            ],
            shuffleIds: [ ],
            playing: false,
            currentTrack: [ ],
            lastTrack: null,
            access: "gm",
            mode: "shuffle",
            delay: 0,
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0"
        },
        MainScore: {
            name: "MainScore",
            trackids: [
                "-LtZ0_krxY6fTsjJdTIY",
                "-LtZ0_klMdDapG40CFa-",
                "-LtZ0_kfks5QpYed16YB",
                "-LtZ0_Pf66HHz8ZzOOJn",
                "-LtZ0_kU19INqgpcurSc",
                "-LtZ0_kOlneli_xHZ7Pb",
                "-LtZ0_kIrmDV0ZkdCbnb",
                "-LtZ0_kAwYus43N3G1cU",
                "-LtZ0_k663N1yaQhDpQp",
                "-LtZ0_k1sx3hxXsQxaYw",
                "-LtZ0_jyoL09lXVhgONz",
                "-LtZ0_jv99WNaPiX1ho2",
                "-LtZ0_jrN8XvHSlm4gB-",
                "-LtZ0_jnAeRWQ7hV4fVa"
            ],
            shuffleIds: [ ],
            playing: true,
            currentTrack: [ "-LtZ0_kAwYus43N3G1cU" ],
            lastTrack: null,
            access: "gm",
            mode: "randomLoop",
            delay: 0,
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: 0
        },
        SplashScreen: {
            name: "SplashScreen",
            trackids: [ "-LtZ0_Pf66HHz8ZzOOJn" ],
            shuffleIds: [ ],
            playing: true,
            currentTrack: [ ],
            lastTrack: null,
            access: "gm",
            mode: "randomLoop",
            delay: 0,
            volume: 15,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0"
        },
        Tag1: {
            name: "Tag1",
            trackids: [ ],
            shuffleIds: [ ],
            playing: false,
            currentTrack: [ ],
            lastTrack: null,
            access: "gm",
            mode: "shuffle",
            delay: 0,
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0"
        },
        Tag2: {
            name: "Tag2",
            trackids: [ ],
            shuffleIds: [ ],
            playing: false,
            currentTrack: [ ],
            lastTrack: null,
            access: "gm",
            mode: "shuffle",
            delay: 0,
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0"
        },
        Tag3: {
            name: "Tag3",
            trackids: [ ],
            shuffleIds: [ ],
            playing: false,
            currentTrack: [ ],
            lastTrack: null,
            access: "gm",
            mode: "shuffle",
            delay: 0,
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0"
        },
        Tag4: {
            name: "Tag4",
            trackids: [ ],
            shuffleIds: [ ],
            playing: false,
            currentTrack: [ ],
            lastTrack: null,
            access: "gm",
            mode: "shuffle",
            delay: 0,
            volume: 100,
            fadeup: 50,
            fadedown: 0,
            fadetime: "0"
        }
    },
    masterVolume: 100,
    fadeVolumeUp: 50,
    fadeVolumeDown: 0,
    fadeTime: "0",
    delay: 0,
    restrict: "on",
    API: "gm",
    access: "None",
    tag: "-players-",
    menu: "tracks",
    nomenu: "On",
    help: "-Lt8c1oc0dtwdyue6fEO"
}